org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=false

minecraft_version=1.10.2
minecraft_version_range=[1.10.2]
forge_version=12.18.3.2511
forge_version_range=[12.18.3.2511,)
loader_version_range=[12,)
mapping_channel=stable
mapping_version=29-1.10.2

loader_name=forge
loader_code=1
java_version=8
java_toolchain_version=8.0.502+7
java_setup_version=8.0.502+7
gradle_java_version=17
curseforge_project_id=240982

mod_id=poweradvantage
mod_name=Power Advantage
mod_license=LGPL-3.0-only
mod_version=2.4.3.110021
mod_group=zone.moddev.mc.poweradvantage
mod_authors=DrCyano (aka Cyanobacterium)
mod_description=API and shared machines for pressure, electricity, quantum power, fluids, and item transport.

cf_requirements=base-metals,mmd-orespawn
cf_optionals=additional-loot-tables
cf_versions=1.10.2

reborncore_version=2.13.6.142
reborncore_curse_project_id=237903
reborncore_curse_file_id=2425028
reborncore_sha256=C7C0D57FFC65B056D3795EBF60912EF5C6333009F33FAEEDA804BE4C22626C99
rf_api_sha256=000BC4DACE68B13BF210177A68F3854C724623EA8F05AC9CDBD9DEBC63ABF62D
orespawn_version=4.0.8.110021
orespawn_source_repository=MinecraftModDevelopmentMods/OreSpawn
orespawn_source_commit=5a50df1158e948c8db55814e819090b34c12d765
orespawn_deobf_sha256=33BFB8C9D626D071147A0952A74B633F0BCC6A27E0408B4524370F4833B003C2
